name: uber_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # --- UI / Core Packages ---
  cupertino_icons: ^1.0.8
  sizer: ^2.0.15
  country_picker: ^2.0.23
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  page_transition: ^2.1.0
  shimmer: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_styled_toast: ^2.2.0
  flutter_swipe_button: ^2.1.1+1
  persistent_bottom_nav_bar_v2: ^6.2.0

  # --- Firebase / Backend ---
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.2
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.1
  firebase_messaging: ^15.1.3

  # --- Utilities ---
  provider: ^6.1.2
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  file_picker: ^8.1.4
  http: ^1.2.2
  uuid: ^4.5.1
  connectivity_plus: ^6.1.1
  google_maps_flutter: ^2.10.2
  geolocator: ^12.0.0
  flutter_polyline_points: ^2.0.0
#  persistent_bottom_nav_bar_v2: ^5.2.2

  image_picker: ^1.1.2
  flutter_geofire: ^2.0.6
  just_audio: ^0.9.42

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/authIcons/
    - assets/images/uberLogo/
    - assets/images/suggestions/
    - assets/images/promotion/
    - assets/images/moreWaysUber/
    - assets/images/planNextTrip/
    - assets/images/saveEveryDay/
    - assets/images/services/
    - assets/images/vehicle/
    - assets/images/icons/
    - assets/sounds/
    - assets/json/customizedMap.json

  fonts:
    - family: UberMoveMedium
      fonts:
        - asset: assets/fonts/UberMoveMedium.otf

    - family: UberMoveBold
      fonts:
        - asset: assets/fonts/UberMoveBold.otf